### ISSUE TITLE
search.retrieval undefined when using minimal download strategy

### ISSUE THREAD

**Issue by Mad-Piggy** [SPCSR/DisplayTemplates#12]
When minimal download strategy is enabled, the first iteration runs without any problem.
But with the 2th iteration search.retrieval is undefined.

Moving the complete search.retrieval = function () {..} to the master page does fix this (dirty fix imo)

Is there a more clean solution to make search.retrieval work with minimal download strategy?

**Comment by wobba** [comment]
@Mad-Piggy Can you let us know which file/template you are referring to.

**Comment by estruyf** [comment]
Another option would be to turn off the minimal download strategy feature on site level.

**Comment by Mad-Piggy** [comment]
@wobba Sorry I'm using "DisplayTemplates/Search Display Templates/Getting past the item limit control template (CSWP)" in my own code. By setting the max number of items above 50 you iterate multiple times over the code within `<div id="Control_List">.`

But due to minimal download strategy you are not able to call search.retrieval.init as it is no longer defined in the 2the iteration.

By moving the compleet search.retrieval in the master page this stays defined and everything is working as expected. Just spit balling and hoping there is a cleaner solution.

@estruyf True but as we are pushing this configuration to multiple sitecollection, this is not maintainable (and not preferred)

**Comment by Danny-Engelman** [comment]
At first glance I  see plenty of sub-namespaces but no ``registerNamespace('search') in the code.
MDS cleans up the Global Namespace on navigation, So I presume everything `search` is wiped.

**Comment by estruyf** [comment]
@Mad-Piggy cannot reproduce this on my environment, can you explain the steps what you do and when it occurs?

**Comment by estruyf** [comment]
@Mad-Piggy any update?

**Comment by Mad-Piggy** [comment]
In [Control_List_All.html](https://github.com/SPCSR/DisplayTemplates/blob/master/Search%20Display%20Templates/Getting%20past%20the%20item%20limit%20control%20template%20(CSWP)/Control_List_All.html) I recieve an error line 82 when requesting more than 50 items.

How to reproduce:
1. Set max items above 50 (in my case 150)
2. Make sure minimal download strategy is enabled
3. Open the page using minimal download strategy. (meaning page is loaded with the # in it)

On initial load `search.retrieval` is created, but when the code in `<div id="Control_List">` is executed ` search.retrieval` is undefined.

No need to search for any other solution, as we rolled out the solution with `search.retrieval` in the master page.

**Comment by estruyf** [comment]
@Danny-Engelman you do not need to register "search" as a namespace first. The register namespace function splits it and registers it part by part.

```
var namespaceParts = namespacePath.split('.');
    for (var i = 0; i < namespaceParts.length; i++) {
```

**Comment by estruyf** [comment]
@Mad-Piggy just want to see if there is a bug fix required. As I cannot reproduce it, I need some extra information. In which browser does this occur? Is it an on-prem or online environment?

**Comment by Mad-Piggy** [comment]
@estruyf Happens in both IE11 and Chrome. And we are using a personal cloud environment.

It can be that this issue is caused by the personal cloud environment provided.

As this is code from a customer, I cannot share nor discuss exact coding.
