### ISSUE TITLE
Unable to load the Delve web part

### ISSUE THREAD

**Issue by haithemhasni** [SPCSR/DisplayTemplates#13]
Hi,

 I have followed your example there and now it is throwing an exception  it now says 
We didn't understand your search terms. Make sure you're using the proper <a href="javascript:HelpWindowKey('WSSEndUser_SearchTips');">syntax</a>.

Do you happen to know where to fix this?
Thank you so much in advance

**Comment by haithemhasni** [comment]
Just FYI :  I have followed the same steps in this link https://www.youtube.com/watch?v=CJo58hU8QfY&feature=youtu.be

**Comment by wobba** [comment]
GQL has been deprecated, so it will stop working soon anyways. So save yourself the trouble to try to get it working :( http://www.techmikael.com/2017/05/the-office-graph-is-dead-long-live.html
