### ISSUE TITLE
Item display template

### ISSUE THREAD

**Issue by milendimo** [SPCSR/DisplayTemplates#3]
Given item display template is applied on each item result in Search, JS usage should very limited in it. All custom logic would be better off in the control template or an external file.

**Comment by sympmarc** [comment]
That's a nice idea, but not practical. If you look at the Display Template architecture, there's inline JavaScript along with the HTML markup. Also, you can't rely on a Content Template being used with the specific Item Template; the goal is for both to stand alone. In practical situations where you have the ability to make that guarantee, adding the JavaScript into the Control Template _might_ work, but only in a general sense, like storing functions.

M.

**Comment by wobba** [comment]
If you call functions, then don't declare them in the item template, but any other js logic with if/else etc is just fine. Common code is better abstracted to the control template or a separate .js lib you link in.

**Comment by Danny-Engelman** [comment]
I don't think this qualifies as an issue. Let's not start a Developer-Patterns war. 
I suggest you Fork what you think is wrong and show us how real men do it.
PS. If you only use the one ctx parameter in a DisplayTemplate and forget about the other 3, you _will_ get some flack from me..
