### ISSUE TITLE
The latest (current) DT script url is not loaded

### ISSUE THREAD

**Issue by mirontoli** [SPCSR/DisplayTemplates#7]
I get the classic [Displayt Template Load Error](http://sharepoint.stackexchange.com/questions/125131/display-error-the-display-template-had-an-error) in the [JavaScript Starter Template](https://github.com/SPCSR/DisplayTemplates/blob/master/Search%20Display%20Templates/JavaScript%20Starter%20Template/Item_Minimal.js)

JavaScript Debugging shows that other scripts are "too fast", e.g. mylinks.js is the latest script. So it doesn't work. I am about to make a fix for that:

![image](https://cloud.githubusercontent.com/assets/470105/14698104/7699818a-078b-11e6-86c0-516770992a0c.png)

**Comment by estruyf** [comment]
Thank you for reporting this. It seems that the SRWP loads in the scripts a bit differently. Your suggested solution isn't fail proof either. It could be that another file from the master page catalog gets loaded. 

Looking into a better solution.
